### ISSUE TITLE
Error in if (grepl("<|>", x)) { : argument is of length zero

### ISSUE THREAD

**Issue by wangwenxia06083** [davidgohel/officer#10]
hi,i have a error like this,i don't know why
`> my_pres <- read_pptx("f:/R_packages_test/test.pptx")`
`>my_pres <- my_pres %>% `
`+ add_slide(layout = "Title and Content", master = "Office Theme")`
**# `Error in if (grepl("<|>", x)) { : argument is of length zero`**

**Comment by davidgohel** [comment]
Hi

This message is because layout = "Title and Content" and master = "Office Theme" are invalid values. You should check the names of your layouts with function `layout_summary`.

However, the error message is not explicit and I made a modification so that you get a clear error message if calling `add_slide` with invalid values. (you can get the new github version)

David

**Comment by wangwenxia06083** [comment]
thank you，my PPT language is  chinese
