### ISSUE TITLE
Documentation around ph_with_ul is not clear

### ISSUE THREAD

**Issue by nathaneastwood** [davidgohel/officer#164]
So I was playing around with a Two Content slide yesterday which had four text boxes in total. I ended up using a combination of the output from `layout_properties` and trial and error to figure out what the [`index`](https://github.com/davidgohel/officer/blob/master/R/ppt_ph_with.R#L217) parameter should equal. I'm not sure whether it should be made clearer within `layout_properties` or the [Roxygen documentation](https://github.com/davidgohel/officer/blob/master/R/ppt_ph_with.R#L217) for `ph_with_ul`. Maybe both? But either way, it was not immediately clear how exactly to determine the `index` number. Some additional information to include would be something along the lines of what the index should be between, i.e. between 1 and the maximum number of elements in a slide. Something like that.

Maybe one idea would be to also accept the `ph_label`, i.e. `Text Placeholder 2`

**Comment by davidgohel** [comment]
Yes. This is a mistake in roxygen documentation. It should inherit param from ph_empty: 
https://github.com/davidgohel/officer/blob/master/R/ppt_ph_with.R#L6

(BTW please let me know if it is a better explanation so that I can improve it if not). I will try to improve the documentation on that point.

About the `ph_label`. Yes, I agree, this has already been suggested but not implemented yet. (But I am starting to work on it right now).

**Comment by davidgohel** [comment]
The new version allows usage of labels - no more index as it seems that was confusing for the users.
