### ISSUE TITLE
Developer documentation?

### ISSUE THREAD

**Issue by rpodcast** [davidgohel/officer#175]
Hello, as I mentioned in my [recent tutorial](https://rpodcast.github.io/officer-advrmarkdown/) I have greatly benefited from `officer` in many key projects at the day job and it has enabled many possibilities for me.  I would like to learn how to contribute development to the package, as I am very interested in the ability to add notes in a powerpoint slide mentioned in #90 and #117.  Do you have resources or other documentation we could review for getting started on helping develop the `officer` package?

**Comment by davidgohel** [comment]
Hi @rpodcast 

Thanks for your message. Your contribution would be welcome! 

Sorry, I don't have documentation for that. 
But I will take time in the following days to write a document so that it will be easier to contribute. 

As a starting point, I recommend reading about the structure that need to be produced: http://officeopenxml.com/prNotesSlide.php

Thanks
David

PS: I need help to maintain and move forward the package because I don't have enough time so again, thanks for helping.

**Comment by davidgohel** [comment]
Hi

Sorry I am not able to provide that documentation. I will re open if I am able to find time for that later.

David
