### ISSUE TITLE
Copy the style of an old docx

### ISSUE THREAD

**Issue by frankzhougq** [davidgohel/officer#195]
Hello,

The package is so amazing and incredibly useful. However, when using the package, I came across a problem. Would you please give me some suggestions?

I have an existing .docx file whose styles I have already defined (Or you could see it as a standard style format which our company is using). I want to use R to create a new docx with the same style of it (like headings, fonts, titles). Here I thought two solutions:
1. Create a new rdocx object and copy the old style information to the new one. But I don’t know how to do it.
2. Directly make changes to the old one and save it as a new docx. In this way, I have to first remove all the texts in the old document. But I don’t know how to use body_remove function to remove all the texts in a convenient way.

Or is there any other way to solve this problem? 

Thank you very much.

**Comment by MajoroMask** [comment]
Hello dear @frankzhougq :

Since you have mentioned that you can achieve your purpose by deleting all contents in an existing template docx. Please try this:

```
library(officer)

docx1 <- "template.docx" %>% read_docx()
for(i in 1:(length(docx1) - 1)) {
  body_remove(docx1)
  cursor_end(docx1)
}
print(docx, target = "blank_template.docx")
```

Since the `rdocx` object is R6 class and its contents are kinda like a list, so simply `body_remove()` from the bottom all the way to the top works just fine. If you open `blank_template.docx` with MS Office Word, you can see it's a blank document with no contents but all the style information preserved.

You can also confirm this by:

```
docx2 <- "blank_template.docx" %>% read_docx()
identical(styles_info(docx1), styles_info(docx2))
#> [1] TRUE
```

**Comment by frankzhougq** [comment]
@MajoroMask 

Thank you so much! It works!
Now my boss will be satisfied with my tiny program.

**Comment by davidgohel** [comment]
thanks @MajoroMask for your help
