### ISSUE TITLE
body_replace_all_text not working when text is broken into chunks

### ISSUE THREAD

**Issue by EDLUT2019** [davidgohel/officer#210]
I would like to suggest an improvement for the body_replace_all_text function to be able to deal with text chunks within a paragraph.

The issue of text chunks is already mentioned in the user manual of the r officer package "Note that the behind-the-scenes representation of text in a Word document is frequently not what you might expect! Sometimes a paragraph of text is broken up (or "chunked") into several "runs," as a result of style changes, pauses in text entry, later revisions and edits, etc..."

I would like to be able to replace text broke into these text chunks.

For instance, I have a Word document with the sentence "Hello Mr <name>!"
However the text is broken into 2 text nodes:
docx_show_chunk(doc)
2 text nodes found at this cursor. 
  <w:t>: 'Hello Mr <'
  <w:t>: 'name>!'

When trying to replace the placeholder <name> by the name Swiss, I will get an error message, because the text is broken into two text nodes:
body_replace_all_text(doc,"<name>","Swiss")

* Content at cursor location:
  level num_id             text style_name content_type
1    NA     NA Hello Mr <name>!         NA    paragraph
Warning message:
In x$doc_obj$replace_all_text(old_value, new_value, only_at_cursor,  :
  Found 0 instances of '<name>' in the document.
I think this issue could be resolved by merging the two text nodes within a paragraph. Perhaps this could be added as an optional parameter to the function body_replace_all_text?

This would be really appreciated.

Thanks a lot.

Mark

**Comment by davidgohel** [comment]
Dear Mark,

> I think this issue could be resolved by merging the two text nodes within a paragraph. Perhaps this could be added as an optional parameter to the function body_replace_all_text?

We did not implement it as it was breaking existing formats and we were not able to preserve formats defined by users and operations that ran before. If you think you can bring a solution, that would be welcome :) Be careful, there is also a performance issue due to xml2 when documents are huge. In the PR, please make sure we understand how you decide when two/tree/four consecutive runs should be merged (will you compare xml properties? I can't see other solutions...).

I am closing that issue and will welcome your PR

KR
David
