### ISSUE TITLE
Blank pptx in PowerPoint, fine in Libre Impress

### ISSUE THREAD

**Issue by mikldk** [davidgohel/officer#287]
I make a pptx file from a png image:

```
library(officer)

full_slide <- function(x, ...){
  ph_with(x = x, ..., location = ph_location_fullsize())
}

pttx_pdf <- read_pptx() %>% 
  add_slide(layout = "Blank", master = "Office Theme")
  full_slide(value = external_img(src = "image.png"))

pttx_pdf %>% print(target = "slides.pptx")
```

When I open `slides.pptx` in LibreOffice Impress I can see the image. When I open it in MS PowerPoint the slide is blank.

See the attached [image.png](https://user-images.githubusercontent.com/7080679/77423060-dc018880-6dce-11ea-8b2c-f20a89acb2b2.png) file and [slides.pptx](https://github.com/davidgohel/officer/files/4375040/slides.pptx) file.

The media is included in the pptx archive (in `ppt/media/`). I am doing something wrong or is there maybe a bug somewhere in the xml files?

**Comment by tvedebrink** [comment]
:+1:

**Comment by davidgohel** [comment]
> When you file a bug report, please spend some time making it easy for me to follow and reproduce. The more time you spend on making the bug report coherent, the more time I can dedicate to investigate the bug as opposed to the bug report.

Your code does not run. I fixed it of course because I don't want a bug to persist if it is really a bug but it requires more times. That's why we are writing guidelines - they can be read when you open a new issue. It's particularly important to:

- [ ] Provide the code that is producing the error, it has to be a minimal reproducible example.
Stackoverflow is providing good explanations about it: https://stackoverflow.com/help/mcve. You can use package `reprex` to help you: http://reprex.tidyverse.org/. The most popular R stackoverflow question is about the subject: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

- [ ] Provide the results of R command `sessionInfo()`. It had to be executed after you loaded the packages used by your example. This will let me know what is your version of R and what are the versions of the packages you used in your example. 

Really sorry for that, I know people don't always get the point but believe me, that's really painful for maintainers. Now I need to go back to work so instead of helping you, I just read your example, saw it was not running and wrote that piece of ranting. No more time left for helping this afternoon. Will come back to you later about your issue. I think it should work and yes, after having fixed your code, the image can not be seen.



```
library(officer)
library(magrittr)

pttx_pdf <- read_pptx() %>% 
  add_slide(layout = "Blank", master = "Office Theme") %>% 
  ph_with(external_img(src = "image.png"), location = ph_location_fullsize())

pttx_pdf %>% print(target = "slides.pptx") 
```

**Comment by mikldk** [comment]
Thanks for the rant - I deserve it not being sufficiently cautious. Thanks again.

**Comment by davidgohel** [comment]
Thanks, that was not obvious to find out what was wrong.

Issue is only happening when using `ph_location_fullsize` with a *blank* layout. You were right, it was a bug in the XML. I added the necessary missing tags and now it's ok.

**Comment by mikldk** [comment]
Thanks for the fast response and solution!

**Comment by tvedebrink** [comment]
Excellent! It works perfectly now :-)

**Comment by davidgohel** [comment]
Thank you both for the feedback
