### ISSUE TITLE
Let the path in read_docx() point to a dotx file

### ISSUE THREAD

**Issue by tomtom** [davidgohel/officer#301]
Currently, the read_docx() function checks that the path has a docx suffix. But word templates are usually saved with as an dotx suffix.

**Comment by davidgohel** [comment]
yes, it's working with a docx file. What issue would that solve?

**Comment by tomtom** [comment]
The function doesn't accept a dotx file as path, although a dotx file is just a docx file with a different suffix.

**Comment by davidgohel** [comment]
Thanks. 

Yes, I understand it is possible. But what would that solve, what is the use case?

**Comment by tomtom** [comment]
Use a template that is not under my control and which ends on dotx, which is the standard for word templates?

**Comment by davidgohel** [comment]
Thanks for the explanation. 

This is not supported for now. If you are stuck with this, you can easily create an empty docx from a dotx file ("save as" in Word). 

There is no plan to integrate that although it could be in the future :)

KR

**Comment by tomtom** [comment]
You are aware of course that this is a one line change?

**Comment by davidgohel** [comment]
Come on, I did not say no, I said not now - and you, are you aware this is voluntary work?

Your behavior is not OK. You only wrote one line of comment, did not read the guidelines (or just did not care), did not explain why I should spend time on it.

This is not one line of code, this is:

- one line of code 
- new tests
- It also needs to be done for PowerPoint
- the documentation (manual at least, vignettes need to be updated with that)
- checks and rev dep checks
- maybe evening work later, like debugging unexpected cases, answering users - even those who think free means free time ;)

The issue for me is not changing a regexp but to maintain that feature. If you want to PR because you are in the hurry (to not "save dotx as docx" once?), please do. I will review it and merge it when ready.

**Comment by tomtom** [comment]
I'm sorry but I actually are in a hurry.
