### ISSUE TITLE
How to preserve rich text when scraping word tables to R?

### ISSUE THREAD

**Issue by FV83** [davidgohel/officer#303]
When importing word tables to R, the text formatting is lost. I have read in the officeR documentation that "the content itself (column text) is a character vector" but is there a way of keeping the formatting (e.g. bold, italics, hyperlinks) when word tables' cells are downloaded. Ideally, I'd like HTML tags and special caracters in my final R object. 

For example, if one cell of the word table is:
More R&D data **available** on the [INSEE website](www.insee.fr])
Then, when I scrap it with officeR - using read_docx(), then docx_summary(), then filter(content_type %in% "table cell")), I get this result in the R table:
"More R&D data available available on the INSEE website"
While I'd like to get this:
More R&amp;amp;D data &lt;strong&gt;available&lt;/strong&gt; on the &lt;a href="www.insee.fr"&gt;INSEE website&lt;/a&gt;

Would it be possible somehow?

Thanks David and congrats - nice package I've just discovered and plan to use for many other applications.

**Comment by davidgohel** [comment]
Thanks for your nice comment,

This is not implemented. `docx_summary` will return a list of text corresponding to each paragraph.  

This is possible but not that easy (if a chunk is formatted as with a style name instead of inline style, you will need to go fishing in styles.xml for example). 

There is no plan to implement that but if you want to contribute, this will be welcome (it may be more relevant in  package docxtractr)
