### ISSUE TITLE
Allow to extract chunks programmatically

### ISSUE THREAD

**Issue by stefanoborini** [davidgohel/officer#305]
docx_show_chunk prints the chunk. This is poor design as the approach should be to deliver the chunks and let the client code print it. A method should be introduced to allow the programmatic retrieval of chunks so that further operation can be done. Specifically, it would be very useful to setup a linting process to verify that no replacement marker is split into two different chunks, preventing the text replacement function to work (which should work regardless, the point of such a library is to abstract away the technical details of the doc format, not bubble them up, but this is a different request)

**Comment by davidgohel** [comment]
This comes from https://github.com/davidgohel/officer/pull/66

I did not want to develop that function but lot of users wanted it, someone nice and constructive took the time to implement it. If you can send a PR to improve that function, it will be welcome. 

I am not able nor volunteer to do it, that's why I am closing the feature request.

**Comment by stefanoborini** [comment]
@davidgohel In general it's a bad idea to close a feature request if you are unable to work on it. Someone else might.
