### ISSUE TITLE
Table interactions in docx

### ISSUE THREAD

**Issue by tpish** [davidgohel/officer#39]
Is there any way to search (and point via cursor, eventually edit) through table cells? The keyword argument to cursor_reach seems to go through the docx's body only.

**Comment by davidgohel** [comment]
No, this is not implemented. 

What is the use case behind the question? Many asked about it only because they wanted to add a border around a title (which is not necessary as paragraphs/titles can have borders), are you in another use case?

**Comment by tpish** [comment]
I am in another use case. 

I have a table inside my docx and I want to fill arbitrary cells with values from R. I have tried to add variable names as placeholders on my table and substitute them through cursor_reach + body_add_fpar (for instance). 

This could be also fixed by a function letting point a cursor to a given table and another to add things to a cell.

**Comment by davidgohel** [comment]
> This could be also fixed by a function letting point a cursor to a given table and another to add things to a cell.

Too tricky, what if you decide to merge cells? Then what if you set the bookmark on 2 consecutives paragraphs, etc...

Did you try package `flextable`? It lets you build any table for Word or PPT...

https://davidgohel.github.io/flextable

**Comment by benvolioT** [comment]
First of all, thank you for the work you've done on officer. Extremely useful, and much appreciated.

I know this issue is closed, but I'll add that this would be a great feature to have.

My use-case is that I'm using a table in my word document to enable a more complex layout of the document. 

I'm actually using [WordR](https://rviews.rstudio.com/2017/10/04/wordr---a-new-r-package-for-rendering-documents-in-ms-word-format/) which builds upon officer by providing a convenience function for replacing r expressions found in the document with their evaluated value.  I'm also using that tool to insert a plot into the table (it finds a bookmark using the cursor_bookmark function).  The table has roughly this structure:

```
---------------------------------------------------------------------
|  Label A | `r value_a` |  Plot Area Here (several merged cells)   |
|  Label B | `r value_b` |                                                                   |
|  Label C | `r value_c` |                                                                   |
|  Label D | `r value_d` |                                                                   |
|  Label E | `r value_e` |                                                                   |
|  Label F | `r value_f` |                                                                   |
---------------------------------------------------------------------
```

The WordR package (and my customizations to it) does not work in a table, which means I can't have this type of custom layout in my document.
