### ISSUE TITLE
Relational layout, or how to get size of a FlexTable/paragraph.

### ISSUE THREAD

**Issue by bescoto** [davidgohel/officer#4]
Hi, thanks for the package, definitely the best way to write PPT!

But is there any way to add one object right below another object?  For instance, suppose I want to put a table and some related bullet points on the same slide.  I can pre-set placeholders for the table and bullet points, but if the table is longer than expected, the table and bullet point may overlap.  If the table is shorter than expected, there might be a lot of whitespace in-between.

In ReporteRs you could specify the x/y coords.  This seems helpful, because if I knew the height of the table I could specify that the bullets be right below it.  But how can you get the height of the table?  I guess you can count the number of rows and multiply by a reasonable number, but the actual size seems to depend on how much word-wrapping occurs (because if a cell wraps around, the cell's row will get taller).

BTW, is officer+flextable recommended over ReporteRs going forward?  Is ReporteRs basically deprecated?  Thanks!

**Comment by davidgohel** [comment]
Hi

Thanks. Yes, this is a missing feature. I hope to be able to implement that soon. 

If working with a flextable, (rows and columns) widths and heights are available (in inches):

```
> x <- flextable(mtcars)
> dim(x)
$widths
      mpg       cyl      disp        hp      drat        wt      qsec        vs        am      gear 
0.2701823 0.1697456 0.2547879 0.1544868 0.2393256 0.1388889 0.2933757 0.1388889 0.1929389 0.2779812 
     carb 
0.2701823 

$heights
 [1] 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236
[10] 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236
[19] 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236
[28] 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236 0.09939236
```

For the Q3, not deprecated, I will maintain it, solve bugs if there are. But I will try to make `officer` and `flextable` better so that ReporteRs users go to officer;). 

Maintaining `ReporteRs` became hard for lot of reasons, most important is java dependency. Also, I have a better understanding of openxml now and it's far easier to do a reboot than to slightly move things and make sure it doesn't break anything important for an existing user. 

So if you can, please use officer instead ReporteRs 👍 

David

**Comment by bescoto** [comment]
Got it, it's a bit of a catch-22 at the moment then: in flextable package you can know the size of tables, but can't specific dynamically where to put stuff; in ReporteRs you can put things at arbitrary coordinates, but you can't know the size of tables!

When flextable gets that functionality we will have the best of both worlds.

Thanks for the response, and for writing great packages!

**Comment by davidgohel** [comment]
Hi,

With new function `ph_with_flextable_at`, flextable objects can be append anywhere on the current slide. No more catch-22!

`officer` and `flextable` will have to be updated from github (or from cran later this week). 

David
