### ISSUE TITLE
In the generated word document, word reports an error that has to be repaired.

### ISSUE THREAD

**Issue by jciconsult** [davidgohel/officer#447]
I have included a log file with sessionInfo and a graphic of the build of Word.  This seems to be a recent issue.
[officer_test.zip](https://github.com/davidgohel/officer/files/9550222/officer_test.zip)
![error_message_word](https://user-images.githubusercontent.com/20973050/189713181-5c7baa25-0a73-4ef6-a0d9-0de16eaddd51.png)
I have tried different variants of the template.  The script is included with the template used in the test example.  All packages are up to date.
I am using word 4.2.1

**Comment by davidgohel** [comment]
This is a recent issue because of https://github.com/davidgohel/officer/commit/f0a4c8ba89cada9cb9241668bbca4abbee129933. Since that version, 'officer' supports properties.

It seems not enough carefully! In your document, you used an incomplete xml string (`<data data-version="3" zotero-version="5.0.60"><session id="P5IjVzb1"/><style id="http://www.zotero.org/styles/chicago-author-date" locale="en-US" hasBibliography="1" bibliographyStyleHasBeenSet="1"/><prefs><pref name="fieldType" value="Field"/><pref name`) in the property named `ZOTERO_PREF_1`.   
<img width="508" alt="Capture d’écran 2022-12-10 à 14 21 55" src="https://user-images.githubusercontent.com/4331618/206857352-86df8f57-7bdd-4998-84e1-13523f98dfc5.png">.  
It ends with `<pref name` which is an incomplete xml set of tags.


It was rewritten *as is* as an XML file and made an incompatible document.

**Comment by davidgohel** [comment]
To reproduce:

[chart_template.docx](https://github.com/davidgohel/officer/files/10200180/chart_template.docx)

```
library(officer)
read_docx(path = "chart_template.docx") |> print(target = "output.docx")
```
