### ISSUE TITLE
ph_empty_at - inherits properties from template

### ISSUE THREAD

**Issue by davidgohel** [davidgohel/officer#47]
https://stackoverflow.com/questions/45088175/in-r-how-to-add-text-to-powerpoint-at-arbitrary-location-so-it-inherits-style

**Comment by davidgohel** [comment]
@bescoto You can use now the new optional arguments `template_type`  and `template_index`.

**Comment by httassadar** [comment]
Could you please explain a bit on how to use `template_index`? 

Since I'll have lots of `body` type, I would like to specify or at least know the index so I can `add_par` to it. But the code below fails and I can't set my own `template_index`

`slides = ph_empty_at(slides, left = 8, top = 4, width = 4, height = 2, template_type = 'body', template_index = 99)`

What I can do is to look at `slide_summary` and manually determine the index

`slides = ph_empty_at(slides, left = 8, top = 4, width = 4, height = 2, template_type = 'body')`
`slides = ph_add_par(slides, type = 'body', id_chr = 6, level = 0)`
