### ISSUE TITLE
autonumbering start again within heading n

### ISSUE THREAD

**Issue by jwijffels** [davidgohel/officer#470]
I must say I've learned a lot from MS Word lately while looking for solutions for different problems which I encountered lately using officer/officedown/flextable. One of them which I couldn't solve without modifying deeply the internals is as follows:

I'm using `officedown::rdocx_document` to generate Word files based on .Rmd's containing chunks with tables (e.g. flextables - with a `tab.cap` or others specified with `block_caption`).

I would like to be able to have table captions and figure captions being numbered as follows 1.1, 1.2, 2.1, 2.2, 2.3 instead of 1.1, 1.2, 2.3, 2.4, 2.5. If I specify the tables - caption - tnd = 1 argument of `officedown::rdocx_document`, this basically passes the printing of the table numbers when rendering the Rmd on to `to_wml.run_autonum` at https://github.com/davidgohel/officer/blob/bae0bc9e6212c8662063473aa2403bfddf85f247/R/ooxml_run_objects.R#L314-L324

For this setting where I would like the second number of the table caption to start again from 1 at the next header 1, I need to have in that part of the code as indicated in the help of [SEQ](https://support.microsoft.com/en-us/office/field-codes-seq-sequence-field-062a387b-dfc9-4ef8-8235-29ee113d59be) the use of `\s` as it resets the sequence number at the heading level following the "s". If I change the officedown code as follows, that gives me a working solution. 

```
seq_str <- paste0("SEQ ", x$seq_id, " \u005C* Arabic \\s 1") and
if(x$tnd != 0){
... paste0("STYLEREF ", x$tnd, " \\s")
}
```

I would like to have this type of option of restarting autonumbering of tables within heading n incorporated in the `officer `package. I see that that would involve changing `run_autonum`, `to_wml.run_autonum`, the printing/knit_print of `flextables`, the options in tables - caption of `officedown::rdocx_document` and maybe some elements more which I'm still lacking like knit_printing to html or other - hopefully not too deeply embedded in knitr for the figure captions (do I miss something - I haven't looked everywhere yet).

Would you be open towards such a change? If so, I'd be happy to implement an extra argument in `run_autonum `or e.g. to let the user set his own options in `SEQ `/ `STYLEREF`.

**Comment by davidgohel** [comment]
I am sorry for the negative answer. We don't want to maintain any additional feature in the captions (there are already 10 options dedicated to Word captions). 

You must know that the captions took us an incredible amount of time. I tried to document as well as possible in `flextable::set_caption()` for example. We spent more time on captions than everything else! There are a hundred of issues related to captions that have been opened in flextable, officer, officedown.

- Today we have to deal with 'Quarto' which changes its behavior very often (they are in dev, it's normal), 'R Markdown' and its specifics, 'bookdown' and its specifics and the requests that have been fulfilled for `officedown'. 
- We had to implemented visual unit-tests to make sure to detect better changes and regressions (see here: https://github.com/davidgohel/flextable/tree/master/tests/testthat/_snaps/md-captions). 

All tools have been made available. In the 'officer' package, the functions `run_word_field`, `fpar()` and many others are available so that users can make what they want if the 'officer' or 'flextable' or 'officedown' functions don't suit them (some illustrations here: https://ardata-fr.github.io/officeverse/paragraphs-chunks.html). 

Mixing calculated references, text with colors, hyperlinks, equations, images, line breaks is already possible... For example, you can use for example `run_word_field()` to get your sequence as you want.

**Comment by jwijffels** [comment]
> I am sorry for the negative answer. We don't want to maintain any additional feature in the captions (there are already 10 options dedicated to Word captions).

No problem. I completely understand this answer. 

> We spent more time on captions than everything else!

Yes, when stepping into the internals to see what I needed, it's incredible to see how knitr settings and the xml are abstracted away and the amount of time to do this and across different packages! :ok_hand:

> All tools have been made available

I'll see if I can brew up something which does not get too much out of synch with the evolution of officer in my local R package, using the `run_` functions. 

Thanks again for the answer and good luck with the Quarto changes :muscle:

**Comment by davidgohel** [comment]
Thank you for your understanding. Don't hesitate to ask if you have any questions about how to use these functions or need a pointer
