### ISSUE TITLE
Remove bookmark in text zone and bkm over multiple paragraphs in Word

### ISSUE THREAD

**Issue by samuel-jobert** [davidgohel/officer#479]
Hi David,
First, thanks for your great package !

I recently updated officer package to version 0.6.0, and removing a bookmark in a text zone (insertion zone de texte in french) does not work anymore, it deletes all the text zones "attached" to the paragraph where they are anchored.

The code I used to remove a bookmark :
```
mydoc <- mydoc %>% cursor_bookmark("signet2")
mydoc <- mydoc %>% body_remove()

```
Regarding your new code, this behavior is normal as cursor_bookmark does not put the cursor on the direct parent paragraph of the bookmark, but put it on the first parent paragraph under body where the text zone is.
And body_remove() deletes this paragraph and everything it contains.

I managed to make it work by writing a function that uses body_remove is the direct parent of the bookmark paragraph is the same as the cursor_bookmark().
If they are not the same, I brutally delete the parent of the bookmark.

```
remove_bookmark = function(x, bkm) {
	expr = sprintf("/descendant::w:bookmarkStart[@w:name='%s']", bkm)
	bkm_node = xml_find_first(x$doc_obj$get(), expr)
	# Si pas trouvé de bookmark, on ne va pas plus loin
	if (inherits(bkm_node, "xml_missing")) {
		stop("Signet ", bkm, " non trouvé !")
	}
	# Recherche du parent (paragraphe) du bookmark (noeud xml)
	bkm_parent = bkm_node %>% xml_parent()

	# On place le curseur sur le bookmark avec la fonction de officer
	x = x %>% cursor_bookmark(bkm)

	# On regarde à quel paragraphe ça correspond
	expr = "/w:document/w:body/*"
	doc_node = xml_find_all(x$doc_obj$get(), expr)[[x$officer_cursor$which]]
	
	# print(bkm_parent)
	# print(doc_node)

	# On compare l'id des paragraphes
	identiques = (bkm_parent %>% xml_attr("paraId")) == (doc_node %>% xml_attr("paraId"))
	
	# S'ils sont identiques, on utilise la fonction body_remove()
	# sinon, on va effacer nous même le paragraphe du bookmark
	if (identiques) {
		x = x %>% body_remove()
	} else {
		bkm_parent %>% xml_remove()
	}
	x
}
```

Do you plan to fix this behavior or implement a (cleaner) function of this type in your package ?

I attached a docx template where I try to remove bookmark "signet2".

Thanks again for your work !
Samuel.

[template_test.docx](https://github.com/davidgohel/officer/files/10941444/template_test.docx)

**Comment by samuel-jobert** [comment]
Hi David,

I managed to create a function (**remove_bookmark()**) that removes bookmarks in document body or in text boxes.
I added the functionality of deleting a bookmark, even if it is on multiple paragraphs.
It deletes the paragraphs from the bookmark start paragraph to the bookmark end paragraph.
It's very useful to me as it permits to delete entire parts of the docx document.

You can check it on my fork : [samuel-jobert/officer](https://github.com/samuel-jobert/officer)
The document I tests this function on is in "test" directory (or attached here).
It contains several bookmarks :
"bkm_in_paragraph" : normal bkm in paragraph in body
"box_bkm_in_paragraph" : bkm in paragraph in text box
"bkm_multi_line" : bkm on multiple pars in body
"box_bkm_multi_line" : bkm in multiple pars in text box


I also added a function that fixes duplicated ids of bookmarks (**fix_bookmark_ids()**).
I don't know why, but I had documents where Word duplicated some ids (it was not a problem for him).
When I tried inserting docx files in that document, it was a mess.

Let me know if you find it useful and if you would like to insert them in your package ;)

[template_for_bookmark_remove.docx](https://github.com/davidgohel/officer/files/10979280/template_for_bookmark_remove.docx)

**Comment by davidgohel** [comment]
Hello

We've spent years trying to meet all our users' replacement needs, to no avail. The result is that one group of users is dissatisfied while the others are happy, and if you move one thing, another group becomes dissatisfied. The users' ultimate motivation is always text replacement. 

To enable text replacement, we have provided functions for simple text replacement without bookmark management:
- the `officer::run_word_field()` function, which allows calculated field insertions
- the `set_doc_properties()` function, which adds values to be replaced in the document (thanks to calculated fields), and goes hand in hand with `doconv::docx_update()`.

For complex insertion at bookmark level :
- for complex sets of blocks, there's always the `block_list()` solution, which lets you insert a set of paragraphs and tables at bookmark level.
- It is always possible to add a bookmark to the bookmark that is to be deleted.

'officer' is quite stable now and we are reluctant to make changes that would break long time existing codes of users or even ours! 

But if you have a PR to suggest, we'll take a look at it and see if we can merge it of course. I understand the value of your suggestion and I fully appreciate it but I don't want to dedicate hours or days for something that is already probably possible with Word computed fields. So we'd like the PR to come with also the help on issues opened by users that will ask enhancements, possible fixes and have questions. Although the request seems strange, it's because we don't want to spend our free open-source time on managing Word bookmarks, I hope you understand :)
