### ISSUE TITLE
docx_summary removes hyphens from text

### ISSUE THREAD

**Issue by daviddiviny** [davidgohel/officer#573]
Please let me know if you need a reprex, but I notice that when extracting tables using docx_summary, any hyphens in words are removed, e.g. "Inspector-General" becomes "InspectorGeneral".

This occurred when extracting tables from the Australian Government Budget at this [link](https://budget.gov.au/content/bp4/download/bp4_05_agency_resourcing_tables.docx).

Thanks to @elipousson  for pointing out that this is probably due to docx_summary not the {officerExtras} package.

**Comment by trekonom** [comment]
The issue is that the hyphens in your table are non breaking hyphens which are added as a [`<noBreakHyphen>`](https://c-rex.net/samples/ooxml/e1/Part4/OOXML_P4_DOCX_noBreakHyphen_topic_ID0EBUCQ.html) element. As a result these hyphens get dropped in `docx_summary` as it only extracts text. I just added a PR with a possible fix. See #575 .
