### ISSUE TITLE
Simpler way to replace text variable inside multiple paragraphs with distinct styles

### ISSUE THREAD

**Issue by rodrigomurta** [davidgohel/officer#60]
First of all, thanks for the amazing package.
One question: It's possible to change a text using find and replace without delete the whole paragraph, and using the actual paragraph style?
For example, I'm using your package to automate comercial offers, and we have the @@clientName@@ variable inside a lot of paragraphs. Today, I have to replace the holly paragraph content, and can't just change @@client@ -> "cliente new" in the whole document, using the current paragraph style.
It would be very helpful to have some way to do that.

**Comment by davidgohel** [comment]
you are welcome!

(sorry, just realized I forgot to update the doc). Function `body_replace_at` can help here but it's not a good candidate if you have many string to update: https://davidgohel.github.io/officer/reference/body_replace_at.html

I will look for a way to do it with Word *field codes* or something similar...

**Comment by rodrigomurta** [comment]
Thanks a lot. This solves part of the problem. Now it's possible to replace text in the middle of a paragraph, and style is not a problem. Very cool.

Full text replace is still very welcome to make easy to replace a variable in the whole document (bookmarks can't be repeated).

**Comment by hangler** [comment]
I just had this problem myself today, and coded up an initial solution on my forked repo — it will do a straight search for an old string amongst all the text nodes in the document and replace with a new string. It even works inside figures (at least, the ones I tested.) @davidgohel, would you be open to a PR with the addition? You can see the comparison here: https://github.com/davidgohel/officer/compare/master...plot-and-scatter:full-search-replace

**Comment by davidgohel** [comment]
I am open to PR but they should not give me additional work ;) Thanks for helping on that subject.

I did not implemented that solution because of the way text is spread into t tags, that's why I was planning to do it with field codes. 

I don't think your solution solve yet that issue. You will have to make sure it works with the following document (replace "move" by "something else"): 
[vicious_test.docx](https://github.com/davidgohel/officer/files/1378657/vicious_test.docx). This is important as users fill a word document the way they want; here I made a pause when typing "move", as a side effect, the document is structured as followed "mo" in a `t` tag and "ve" in the following `t` tag.

About rvg figures, please make sure their text is not replaced! There are font metrics calculations and changing the text will have side effects on the rendering (changing the text will not change the position...)

Minor comments: 

- Why are you dropping the first `t` from the replacement process? (https://github.com/davidgohel/officer/compare/master...plot-and-scatter:full-search-replace#diff-c234b612c74289cfdc71342ef058a190R126)
- I don't think the `paste` is necessary: https://github.com/davidgohel/officer/compare/master...plot-and-scatter:full-search-replace#diff-c234b612c74289cfdc71342ef058a190R123
- `gsub` arguments could have default values implemented in the function call and not hard-coded. Some users are experienced with regexpr and want to get control over it.
- can you warn the user if no match has been found? 

What is the behavior on huge documents (like 500 pages as pharmaceutical companies like)? I have users that are using i386 Windows architecture with not more than 4G. I am not sure this is a relevant issue but maybe a short comment that warn the user this is raw replacement and could be ressource consuming. 

Could you also update vignettes and pkgdown file. 

This will also need to be tested in "tests" directory (with an example like `vicious_test.docx`, maybe also with a big Word file).

Thanks

**Comment by hangler** [comment]
Thanks for the feedback and openness!

I am an absolute beginner when it comes to behind-the-scenes Word doc structure, so it's good to know about the text splitting, as it didn't come up as an issue in the doc I was working with. It seems the "user pausing while typing" issue might be solved by merging adjacent `r` tags within (I now understand better that that's what you do in `cursor_replace_first_text`, right?) so I will look into the feasibility there. Does that basically destroy any within-paragraph styling and any `w:rsidRPr` attributes, and is that OK?

Those first two minor comments you list (the links don't work for me, but I think I know what you're referring to) are due to some copy-and-paste silliness on my part.

Will work on the fixes/enhancements you suggest over the next few days and submit a PR when ready. And hopefully not create too much extra work for you 😉

**Comment by davidgohel** [comment]
> Does that basically destroy any within-paragraph styling and any w:rsidRPr attributes, and is that OK?

unfortunately yes...

I think the cost and issues you will meet are not worth the gain. Make it work without considering "user pausing while typing" issue and add a function `docx_show_chunk` that shows to the user the underlying chunks of text. 

This how I see things after my day:

1. fix everything in your PR so that the function can replace text with regular expression. Consider there is no issue with split text along "<w:t>". 
2. add a function `docx_show_chunk` to let user view how the text is separated along "<w:t>". This analyse the paragraph defined by the cursor.
3. Document the 2 new functions - not with my english but yours;) It will be better
4. run `R CMD check` and `rhub::check_for_cran()` (on your version change the email so that you will receive the email and not me)
4. post the PR
5. I will help you with other details if needed :)

Thanks

**Comment by hangler** [comment]
Thanks for that! Here's the PR: https://github.com/davidgohel/officer/pull/66

We can move this discussion to the PR thread, if you'd like?

**Comment by davidgohel** [comment]
provided by @hangler in `body_replace_all_text`
