### ISSUE TITLE
having trouble with the new function (body_replace_all_text)

### ISSUE THREAD

**Issue by fabianaboldrin** [davidgohel/officer#75]
The last implemented function (body_replace_all_text) was created in a very good time, it solved a lot of problems that I was having with generating dynamic sales proposals, where I needed to replace more than one time the same word. I'm just having a little hard time using it because probably it is not working as it should. 

For exemple in this text:
![screen shot 2017-10-23 at 17 11 31](https://user-images.githubusercontent.com/29741664/31908351-4b913cd0-b815-11e7-959c-dbc80de191ac.png)

I used the following code for replacing the target-words:

`body_replace_all_text(my_doc, "@replace", "123", ignore.case = TRUE, onlyAtCursor = FALSE)`

The result was:
![screen shot 2017-10-23 at 17 05 34](https://user-images.githubusercontent.com/29741664/31908067-72a75b8e-b814-11e7-8cf6-5e0bf186efe6.png)

**Comment by hangler** [comment]
Hi there. I reproduced your example in a test document (attached) and then ran the command you supplied. The output (also attached) looks correct in my version.

Please check, using the `cursor_*` commands and `docx_show_chunk()`, that your text isn't chunked into multiple runs (see the help file for `body_replace_all_text` for more on this). That's the most likely reason for a search-and-replace failure.

[test.docx](https://github.com/davidgohel/officer/files/1408525/test.docx)
[output.docx](https://github.com/davidgohel/officer/files/1408526/output.docx)

**Comment by fabianaboldrin** [comment]
The output that I had when using `docx_show_chunk()` at my test doc was:
`4 text nodes found at this cursor.`
`<w:t>: 'foo@'`
`<w:t>: 'replace@'`
`<w:t>: 'replace'`
`<w:t>: 'bar'`

And when I did the same test for your test doc I received:
`1 text nodes found at this cursor.`
`<w:t>: 'foo123123bar'`

How can I have the same output for achieving the same result in the replacement?

**Comment by hangler** [comment]
OK, that's expected (if undesired). To be clear, the problem is that the `@` text is not in the same chunk as the `replace` text — so searching for `@replace` doesn't find a match.

The easiest way to fix this problem is to select the entire line of text in question, copy-and-paste it into a text editor (such as Notepad, TextEdit), and then copy-and-paste from the text editor back into Word, replacing the previous content.

If you then re-load the doc, navigate the cursor the line in question, and run `docx_show_chunk()`, you should get output like this:

```r
1 text nodes found at this cursor.
  <w:t>: 'foo@replacebar@replace'
```

**Comment by hangler** [comment]
@davidgohel I think this issue can be closed.
